
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COLON COMMA DEF ID LPAREN RPARENfunction : DEF ID LPAREN parameter_list RPAREN COLON\n    parameter_list : parameter_list COMMA ID\n                   | ID\n                   | empty\n    empty :'
    
_lr_action_items = {'DEF':([0,],[2,]),'$end':([1,10,],[0,-1,]),'ID':([2,4,9,],[3,5,11,]),'LPAREN':([3,],[4,]),'RPAREN':([4,5,6,7,11,],[-5,-3,8,-4,-2,]),'COMMA':([4,5,6,7,11,],[-5,-3,9,-4,-2,]),'COLON':([8,],[10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'function':([0,],[1,]),'parameter_list':([4,],[6,]),'empty':([4,],[7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> function","S'",1,None,None,None),
  ('function -> DEF ID LPAREN parameter_list RPAREN COLON','function',6,'p_function_definition','func-def.py',46),
  ('parameter_list -> parameter_list COMMA ID','parameter_list',3,'p_parameter_list','func-def.py',51),
  ('parameter_list -> ID','parameter_list',1,'p_parameter_list','func-def.py',52),
  ('parameter_list -> empty','parameter_list',1,'p_parameter_list','func-def.py',53),
  ('empty -> <empty>','empty',0,'p_empty','func-def.py',57),
]
