
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN COLON DEDENT EQ ID IF INDENT INTstatement : IF ID EQ INT COLON ID ASSIGN INT'
    
_lr_action_items = {'IF':([0,],[2,]),'$end':([1,9,],[0,-1,]),'ID':([2,6,],[3,7,]),'EQ':([3,],[4,]),'INT':([4,8,],[5,9,]),'COLON':([5,],[6,]),'ASSIGN':([7,],[8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> IF ID EQ INT COLON ID ASSIGN INT','statement',8,'p_statement_if','if.py',49),
]
