
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COLON EQ GT ID LT N NUMBER TRUE WHILEwhile_loop : WHILE ID LT NUMBER COLON\n                  | WHILE ID LT N COLON\n                  | WHILE ID GT NUMBER COLON\n                  | WHILE ID GT N COLON\n                  | WHILE ID EQ NUMBER COLON\n                  | WHILE ID EQ N COLON\n                  | WHILE NUMBER GT ID COLON\n                  | WHILE NUMBER LT ID COLON\n                  | WHILE NUMBER EQ ID COLON\n                  | WHILE N GT ID COLON\n                  | WHILE N LT ID COLON\n                  | WHILE N EQ ID COLON\n                  | while_truewhile_true : WHILE TRUE COLON'
    
_lr_action_items = {'WHILE':([0,],[2,]),'$end':([1,3,17,30,31,32,33,34,35,36,37,38,39,40,41,],[0,-13,-14,-1,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,-12,]),'ID':([2,11,12,13,14,15,16,],[4,24,25,26,27,28,29,]),'NUMBER':([2,8,9,10,],[5,18,20,22,]),'N':([2,8,9,10,],[6,19,21,23,]),'TRUE':([2,],[7,]),'LT':([4,5,6,],[8,12,15,]),'GT':([4,5,6,],[9,11,14,]),'EQ':([4,5,6,],[10,13,16,]),'COLON':([7,18,19,20,21,22,23,24,25,26,27,28,29,],[17,30,31,32,33,34,35,36,37,38,39,40,41,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'while_loop':([0,],[1,]),'while_true':([0,],[3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> while_loop","S'",1,None,None,None),
  ('while_loop -> WHILE ID LT NUMBER COLON','while_loop',5,'p_while_loop','while.py',44),
  ('while_loop -> WHILE ID LT N COLON','while_loop',5,'p_while_loop','while.py',45),
  ('while_loop -> WHILE ID GT NUMBER COLON','while_loop',5,'p_while_loop','while.py',46),
  ('while_loop -> WHILE ID GT N COLON','while_loop',5,'p_while_loop','while.py',47),
  ('while_loop -> WHILE ID EQ NUMBER COLON','while_loop',5,'p_while_loop','while.py',48),
  ('while_loop -> WHILE ID EQ N COLON','while_loop',5,'p_while_loop','while.py',49),
  ('while_loop -> WHILE NUMBER GT ID COLON','while_loop',5,'p_while_loop','while.py',50),
  ('while_loop -> WHILE NUMBER LT ID COLON','while_loop',5,'p_while_loop','while.py',51),
  ('while_loop -> WHILE NUMBER EQ ID COLON','while_loop',5,'p_while_loop','while.py',52),
  ('while_loop -> WHILE N GT ID COLON','while_loop',5,'p_while_loop','while.py',53),
  ('while_loop -> WHILE N LT ID COLON','while_loop',5,'p_while_loop','while.py',54),
  ('while_loop -> WHILE N EQ ID COLON','while_loop',5,'p_while_loop','while.py',55),
  ('while_loop -> while_true','while_loop',1,'p_while_loop','while.py',56),
  ('while_true -> WHILE TRUE COLON','while_true',3,'p_while_true','while.py',60),
]
